### ISSUE TITLE
Segfaulting: Threshold between CharPoly algorithms LUKrylov <-> ArithProg 

### ISSUE THREAD

**Issue by jgdumas** [linbox-team/fflas-ffpack#266]
```
Threshold between CharPoly algorithms LUKrylov <-> ArithProg (using ModularBalanced<double> mod 131071)

Charpoly:  n                   LUKrylov                        ArithProg
                    seconds            Gfops          seconds            Gfops

Program received signal SIGSEGV, Segmentation fault.
__memmove_avx_unaligned_erms () at ../sysdeps/x86_64/multiarch/memmove-vec-unaligned-erms.S:262
262	../sysdeps/x86_64/multiarch/memmove-vec-unaligned-erms.S: Aucun fichier ou dossier de ce type.
(gdb) where
#0  __memmove_avx_unaligned_erms () at ../sysdeps/x86_64/multiarch/memmove-vec-unaligned-erms.S:262
#1  0x00007ffff7a156f3 in dcopy_ () from /tmp/linbox/build/blis/lib/haswell/libblis.so.2
#2  0x00007ffff7a28e55 in cblas_dcopy () from /tmp/linbox/build/blis/lib/haswell/libblis.so.2
#3  0x000055555555aad0 in FFLAS::fassign<Givaro::ModularBalanced<double> > (F=..., incX=1, X=<optimized out>, incY=1, Y=0x5555565d4720, N=1024) at ../fflas-ffpack/fflas/fflas_fassign.inl:137
#4  FFLAS::fassign<Givaro::ModularBalanced<double> > (F=..., m=1024, n=1024, B=<optimized out>, ldb=<optimized out>, A=<optimized out>, lda=1024) at ../fflas-ffpack/fflas/fflas_fassign.inl:177
#5  0x000055555557c3a8 in FFPACK::Protected::ArithProg<Givaro::Poly1Dom<Givaro::ModularBalanced<double>, Givaro::Dense> > (PR=..., frobeniusForm=empty std::__cxx11::list, N=N@entry=1024, A=A@entry=0x7ffff2da7040, lda=3000, degree=degree@entry=1) at ../fflas-ffpack/utils/fflas_memory.h:69
#6  0x000055555558449f in FFPACK::CharPoly<Givaro::Poly1Dom<Givaro::ModularBalanced<double>, Givaro::Dense> > (G=..., CharpTag=FFPACK::FfpackArithProg, degree=30, lda=<optimized out>, A=0x7ffff2da7040, N=1024, charp=empty std::__cxx11::list, R=...) at ../fflas-ffpack/ffpack/ffpack_charpoly.inl:53
#7  FFPACK::CharPoly<Givaro::Poly1Dom<Givaro::ModularBalanced<double>, Givaro::Dense> > (R=..., charp=empty std::__cxx11::list, N=1024, A=0x7ffff2da7040, lda=3000, G=..., CharpTag=FFPACK::FfpackArithProg, degree=30) at ../fflas-ffpack/ffpack/ffpack_charpoly.inl:53
#8  0x0000555555559075 in FFPACK::CharPoly<Givaro::Poly1Dom<Givaro::ModularBalanced<double>, Givaro::Dense> > (degree=30, CharpTag=FFPACK::FfpackArithProg, G=..., lda=3000, A=0x7ffff2da7040, N=1024, charp=std::vector of length 1025, capacity 1025 = {...}, R=...) at /usr/include/c++/8/bits/stl_list.h:153
#9  FFPACK::CharPoly<Givaro::Poly1Dom<Givaro::ModularBalanced<double>, Givaro::Dense> > (degree=30, CharpTag=FFPACK::FfpackArithProg, lda=3000, A=0x7ffff2da7040, N=1024, charp=std::vector of length 1025, capacity 1025 = {...}, R=...) at ../fflas-ffpack/ffpack/ffpack.h:1043
#10 main () at charpoly.C:103
=============================================================

Same with OpenBlas
=============================================================
Threshold between CharPoly algorithms LUKrylov <-> ArithProg (using ModularBalanced<double> mod 131071)

Charpoly:  n                   LUKrylov                        ArithProg
                    seconds            Gfops          seconds            Gfops

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff70a54cb in dcopy_k ()
   from /usr/local/soft/OpenBLAS/lib/libopenblas.so.0
(gdb) where
#0  0x00007ffff70a54cb in dcopy_k ()
   from /usr/local/soft/OpenBLAS/lib/libopenblas.so.0
#1  0x000055555555aaea in FFLAS::fassign<Givaro::ModularBalanced<double> > (
    F=..., incX=1, X=<optimized out>, incY=1, Y=0x5555565d6720, N=1024)
    at ../fflas-ffpack/fflas/fflas_fassign.inl:137
#2  FFLAS::fassign<Givaro::ModularBalanced<double> > (F=..., m=1024, n=1024, 
    B=<optimized out>, ldb=<optimized out>, A=<optimized out>, lda=1024)
    at ../fflas-ffpack/fflas/fflas_fassign.inl:177
#3  0x000055555557c6cb in FFPACK::Protected::ArithProg<Givaro::Poly1Dom<Givaro::ModularBalanced<double>, Givaro::Dense> > (PR=..., Python Exception <class 'ValueError'> Cannot find type class std::__cxx11::list<std::vector<double, std::allocator<double> >, std::allocator<std::vector<double, std::allocator<double> > > >::_Node: 

    frobeniusForm=empty std::__cxx11::list, N=N@entry=1024, 
    A=A@entry=0x7ffff1fe9040, lda=3000, degree=degree@entry=1)
    at ../fflas-ffpack/utils/fflas_memory.h:69
#4  0x0000555555584bcf in FFPACK::CharPoly<Givaro::Poly1Dom<Givaro::ModularBalanced<double>, Givaro::Dense> > (G=..., CharpTag=FFPACK::FfpackArithProg, 
    degree=30, lda=<optimized out>, A=0x7ffff1fe9040, N=1024, Python Exception <class 'ValueError'> Cannot find type class std::__cxx11::list<std::vector<double, std::allocator<double> >, std::allocator<std::vector<double, std::allocator<double> > > >::_Node: 

    charp=empty std::__cxx11::list, R=...)
    at ../fflas-ffpack/ffpack/ffpack_charpoly.inl:53
#5  FFPACK::CharPoly<Givaro::Poly1Dom<Givaro::ModularBalanced<double>, Givaro::Dense> > (R=..., Python Exception <class 'ValueError'> Cannot find type class std::__cxx11::list<std::vector<double, std::allocator<double> >, std::allocator<std::vector<double, std::allocator<double> > > >::_Node: 
charp=empty std::__cxx11::list, N=1024, A=0x7ffff1fe9040, 
    lda=3000, G=..., CharpTag=FFPACK::FfpackArithProg, degree=30)
    at ../fflas-ffpack/ffpack/ffpack_charpoly.inl:53
--Type <RET> for more, q to quit, c to continue without paging--
ced<double>, Givaro::Dense> > (degree=30, CharpTag=FFPACK::FfpackArithProg, G=..., lda=3000, A=0x7ffff1fe9040, N=1024, charp=std::vector of length 1025, capacity 1025 = {...}, R=...) at /usr/include/c++/8/bits/stl_list.h:153
#7  FFPACK::CharPoly<Givaro::Poly1Dom<Givaro::ModularBalanced<double>, Givaro::Dense> > (degree=30, CharpTag=FFPACK::FfpackArithProg, lda=3000, A=0x7ffff1fe9040, N=1024, charp=std::vector of length 1025, capacity 1025 = {...}, R=...) at ../fflas-ffpack/ffpack/ffpack.h:1043
#8  main () at charpoly.C:103
```

**Comment by ClementPernet** [comment]
fixed in 469a0411b87dcbc9f9b4d66fe3d928486b41b5d8
